### ISSUE TITLE
Errors on Import

### ISSUE THREAD

**Issue by Ritchie-Audio** [fross123/csv_to_qlab#104]
**Describe the bug**
Unable to import simple.csv into Qlab 5.4.4

165 errors reading as shown below.

Error Status: denied
/reply/new: ('{"address":"|Vworkspace|VEE1BF820-B6AB-424C-
AD4C-
F5522AD82A91\Vnew","status":"denied" "workspace_id":"EE1BF820-
B6AB-424C-AD4C-F5522AD82A91"'}',)

**To Reproduce**
1. I followed the online instructions

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 14.5

**Comment by fross123** [comment]
Hi there @Ritchie-Audio. QLab 5 has a passcode set by default. The "denied" status is a response from QLab, and the most frequent culprit is the passcode.

Please try either removing the passcode in your QLab workspace, or enter the passcode in CSV-to-QLab.

Thanks for reporting your issue! Let me know if this works for you.

**Comment by fross123** [comment]
Hello, it's been a few weeks so I'm going to close this issue for now. Let me know if the passcode was not the problem, and I will happily re-open the issue.

Fin
