### ISSUE TITLE
when running locally, port should be printed to the console

### ISSUE THREAD

**Issue by weaversam8** [fross123/csv_to_qlab#75]
In case the webview doesn't open successfully, the randomly-selected Flask port should be printed to the console so devs can open the UI in their browser.

**Comment by fross123** [comment]
Is the webview not opening successfully for you?

This app uses pywebview, which has a debugging parameter that is easily added if the browser inspector is needed for some reason.
Details here: https://pywebview.flowrl.com/guide/debugging.html

If you would like to run in development without the webview, I suggest using Flask's development server. In our case, you would run `flask --app application.py run` which will allow you to run the application in a browser.

I'm closing this issue for now, but let me know if neither of these options do what you are hoping to do and we can discuss further.
